services:
  - type: web
    name: patent-ai-assistant
    env: python
    plan: free
    region: singapore
    buildCommand: |
      pip install -r requirements.txt
      pip install streamlit
    startCommand: |
      streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
